[target.'cfg(any(unix, not(unix))']
rustflags = ["-Zmacro-backtrace", "-Zdebug-macros"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Zmacro-backtrace",
    "-Zdebug-macros"
#    "-C",
#    "link-arg=-fuse-ld=mold"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-Zmacro-backtrace",
    "-Zdebug-macros",
    "-Zthreads=10"
#   "-C",
#   "link-arg=-fuse-ld=mold",
#   "--cfg",
#   "tokio_unstable"
]

[term]
verbose = false
color = 'auto'
