[target.'cfg(any(unix, not(unix))']
rustflags = ["-Zmacro-backtrace", "-Zdebug-macros"]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-Zmacro-backtrace",
    "-Zdebug-macros", 
    "-Zthreads=4",
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "target-cpu=native"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-Zmacro-backtrace",
    "-Zdebug-macros",
    "-Zthreads=8",
    "-C",
    "target-cpu=native"
#   "-C",
#   "link-arg=-fuse-ld=mold",
#   "--cfg",
#   "tokio_unstable"
]

[term]
verbose = false
color = 'auto'
